//edition = "2024";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: chips.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Dist          map[int32]float64      `protobuf:"bytes,2,rep,name=dist,proto3" json:"dist,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // key单位为分的价格, value是成交量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chips) Reset() {
	*x = Chips{}
	mi := &file_chips_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chips) ProtoMessage() {}

func (x *Chips) ProtoReflect() protoreflect.Message {
	mi := &file_chips_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chips.ProtoReflect.Descriptor instead.
func (*Chips) Descriptor() ([]byte, []int) {
	return file_chips_proto_rawDescGZIP(), []int{0}
}

func (x *Chips) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Chips) GetDist() map[int32]float64 {
	if x != nil {
		return x.Dist
	}
	return nil
}

type ChipDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*Chips      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key是日期, value是chips的map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChipDistribution) Reset() {
	*x = ChipDistribution{}
	mi := &file_chips_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChipDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChipDistribution) ProtoMessage() {}

func (x *ChipDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_chips_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChipDistribution.ProtoReflect.Descriptor instead.
func (*ChipDistribution) Descriptor() ([]byte, []int) {
	return file_chips_proto_rawDescGZIP(), []int{1}
}

func (x *ChipDistribution) GetData() map[string]*Chips {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_chips_proto protoreflect.FileDescriptor

var file_chips_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x63, 0x68, 0x69, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x7d, 0x0a, 0x05, 0x43, 0x68, 0x69, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x64, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x68, 0x69, 0x70, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x64, 0x69, 0x73, 0x74, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x8a, 0x01, 0x0a, 0x10, 0x43, 0x68, 0x69, 0x70, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x69, 0x70, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x42, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x69,
	0x70, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_chips_proto_rawDescOnce sync.Once
	file_chips_proto_rawDescData []byte
)

func file_chips_proto_rawDescGZIP() []byte {
	file_chips_proto_rawDescOnce.Do(func() {
		file_chips_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chips_proto_rawDesc), len(file_chips_proto_rawDesc)))
	})
	return file_chips_proto_rawDescData
}

var file_chips_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chips_proto_goTypes = []any{
	(*Chips)(nil),            // 0: pb.Chips
	(*ChipDistribution)(nil), // 1: pb.ChipDistribution
	nil,                      // 2: pb.Chips.DistEntry
	nil,                      // 3: pb.ChipDistribution.DataEntry
}
var file_chips_proto_depIdxs = []int32{
	2, // 0: pb.Chips.dist:type_name -> pb.Chips.DistEntry
	3, // 1: pb.ChipDistribution.data:type_name -> pb.ChipDistribution.DataEntry
	0, // 2: pb.ChipDistribution.DataEntry.value:type_name -> pb.Chips
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chips_proto_init() }
func file_chips_proto_init() {
	if File_chips_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chips_proto_rawDesc), len(file_chips_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chips_proto_goTypes,
		DependencyIndexes: file_chips_proto_depIdxs,
		MessageInfos:      file_chips_proto_msgTypes,
	}.Build()
	File_chips_proto = out.File
	file_chips_proto_goTypes = nil
	file_chips_proto_depIdxs = nil
}
